const StorageKeys = {
  USER: 'user',
  TOKEN: 'access_token',
  // NEXT_PUBLIC_GOOGLE_MAPS_API_KEY: 'AIzaSyDRX0D21tjCpNmpABQp8bnfNyA99pscQrM',
  NEXT_PUBLIC_GOOGLE_MAPS_API_KEY: 'AIzaSyDNI_ZWPqvdS6r6gPVO50I4TlYkfkZdXh8', //1
  // NEXT_PUBLIC_GOOGLE_MAPS_API_KEY: 'AIzaSyDaOulQACiJzBfqumbsqg_-vKha8fCnL-s', //2
  // NEXT_PUBLIC_GOOGLE_MAPS_API_KEY: 'AIzaSyDc7PnOq3Hxzq6dxeUVaY8WGLHIePl0swY', //3
  // NEXT_PUBLIC_GOOGLE_MAPS_API_KEY: 'AIzaSyDWTx7bREpM5B6JKdbzOvMW-RRlhkukmVE', //4
  // NEXT_PUBLIC_GOOGLE_MAPS_API_KEY: 'AIzaSyCJqpC7oo-YYJJ1pRVZJgf84qExlHZCWSc', //5
  // NEXT_PUBLIC_GOOGLE_MAPS_API_KEY: 'AIzaSyA66KwUrjxcFG5u0exynlJ45CrbrNe3hEc', //6
  // NEXT_PUBLIC_GOOGLE_MAPS_API_KEY: 'AIzaSyBS6lGj7CsMDE5O9bMEf3I3anmfn34OBlA', //7

  // NEXT_PUBLIC_GOOGLE_MAPS_API_KEY: 'AIzaSyDb5xOZiLOJAtKJWj4spvQf3UEQvE-3sc4', // Sỹ bùi
  // NEXT_PUBLIC_GOOGLE_MAPS_API_KEY: 'AIzaSyAI9kPkskayYti5ttrZL_UfBlL3OkMEbvs', //
};

export default StorageKeys;
