const StorageKeys = {
  USER: 'user',
  TOKEN: 'access_token',
  // NEXT_PUBLIC_GOOGLE_MAPS_API_KEY: 'AIzaSyDRX0D21tjCpNmpABQp8bnfNyA99pscQrM',
  // NEXT_PUBLIC_GOOGLE_MAPS_API_KEY: 'AIzaSyDNI_ZWPqvdS6r6gPVO50I4TlYkfkZdXh8', //1
  // NEXT_PUBLIC_GOOGLE_MAPS_API_KEY: 'AIzaSyDaOulQACiJzBfqumbsqg_-vKha8fCnL-s', //2
  // NEXT_PUBLIC_GOOGLE_MAPS_API_KEY: 'AIzaSyDc7PnOq3Hxzq6dxeUVaY8WGLHIePl0swY', //3
  // NEXT_PUBLIC_GOOGLE_MAPS_API_KEY: 'AIzaSyDWTx7bREpM5B6JKdbzOvMW-RRlhkukmVE', //4
  // NEXT_PUBLIC_GOOGLE_MAPS_API_KEY: 'AIzaSyCJqpC7oo-YYJJ1pRVZJgf84qExlHZCWSc', //5
  // NEXT_PUBLIC_GOOGLE_MAPS_API_KEY: 'AIzaSyA66KwUrjxcFG5u0exynlJ45CrbrNe3hEc', //6
  // NEXT_PUBLIC_GOOGLE_MAPS_API_KEY: 'AIzaSyBS6lGj7CsMDE5O9bMEf3I3anmfn34OBlA', //7

  NEXT_PUBLIC_GOOGLE_MAPS_API_KEY: 'AIzaSyDb5xOZiLOJAtKJWj4spvQf3UEQvE-3sc4', // Sỹ bùi
  // NEXT_PUBLIC_GOOGLE_MAPS_API_KEY: 'AIzaSyA4U7NiEGbOGvkdyaVJ1tbKAAWBB9uz7uA', // Quang Huy
  // NEXT_PUBLIC_GOOGLE_MAPS_API_KEY: 'AIzaSyCPgjso1A3rEuIAg2SdNz9fhHtBzkBZzF4', // Quang Huy 2
  // NEXT_PUBLIC_GOOGLE_MAPS_API_KEY: 'AIzaSyCBtdOlSHheuzu_nmuOku_BIzc4_q2Gx5E', // Quang Huy 3
  // NEXT_PUBLIC_GOOGLE_MAPS_API_KEY: 'AIzaSyAcygHzAe_KRtKoqMEv4gyF05YXeUZl4gc', // Trần Tiến
  // NEXT_PUBLIC_GOOGLE_MAPS_API_KEY: 'AIzaSyBBe98uaYmZZ1pYXM8WGfr3mmRTTf3NBxA', // wiro
  // NEXT_PUBLIC_GOOGLE_MAPS_API_KEY: 'AIzaSyCuS20tP_3x_HeCequgVkVm6oKuonAhtW4', // youtube

  // twitter
  // NEXT_PUBLIC_GOOGLE_MAPS_API_KEY: 'AIzaSyA3bsDl1xddiU_w38hA-fsGea8kWsp5uJM', // wiro
  // NEXT_PUBLIC_GOOGLE_MAPS_API_KEY: 'AIzaSyB41WOlRVKsPo0ZCoznE3qvwQ-AkWoONIY', // wiro
  // NEXT_PUBLIC_GOOGLE_MAPS_API_KEY: 'AIzaSyDDGnGXfMSJASUkudAzyIjaOXuCeWxxyN0', // wiro

  // NEXT_PUBLIC_GOOGLE_MAPS_API_KEY: 'AIzaSyDpuhPAXBFKTzK1P7n9vSW87mZtZBSG408',
  // NEXT_PUBLIC_GOOGLE_MAPS_API_KEY: 'AIzaSyAMzJJT-79_hGUbNOXaA4GwIB0Z7hb8PPU',
  // NEXT_PUBLIC_GOOGLE_MAPS_API_KEY: 'AIzaSyC_vNaM21XXwjYpQ_7kMYCYsFg8w2gMqK0', //
  // NEXT_PUBLIC_GOOGLE_MAPS_API_KEY: 'AIzaSyCcm1-tm594tu_GAMv_9uk6OznoyMGpWSc', //
  // NEXT_PUBLIC_GOOGLE_MAPS_API_KEY: 'AIzaSyCG2YHIuPJYMOJzS6wSw5eZ0dTYXnhZFLs', //
  // NEXT_PUBLIC_GOOGLE_MAPS_API_KEY: 'AIzaSyAI9kPkskayYti5ttrZL_UfBlL3OkMEbvs', //

  // NEXT_PUBLIC_GOOGLE_MAPS_API_KEY: 'AIzaSyCdFMMdGRCiOrGZrK28JOv5bSq9ueG8Cgw', //

  // NEXT_PUBLIC_GOOGLE_MAPS_API_KEY: '5db886fd-4d3e-410c-b823-f754604424e2', //
  // NEXT_PUBLIC_GOOGLE_MAPS_API_KEY: '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', //
};

export default StorageKeys;
